# Generated by Django 5.2.4 on 2026-03-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0036_alter_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(help_text='The slug of the deleted/old news post', max_length=255, unique=True)),
                ('redirect_slug', models.SlugField(help_text='The slug to redirect to (similar news post)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this redirect')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about why this redirect was created', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
